#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x43EC92504F71955A (dave@dajobe.org)
#
Name     : redland
Version  : 1.0.17
Release  : 7
URL      : http://download.librdf.org/source/redland-1.0.17.tar.gz
Source0  : http://download.librdf.org/source/redland-1.0.17.tar.gz
Source1  : http://download.librdf.org/source/redland-1.0.17.tar.gz.asc
Summary  : Redland RDF Application Framework
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 LGPL-2.1 LGPL-2.1+
Requires: redland-bin = %{version}-%{release}
Requires: redland-data = %{version}-%{release}
Requires: redland-lib = %{version}-%{release}
Requires: redland-license = %{version}-%{release}
Requires: redland-man = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : mariadb-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(raptor2)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : postgresql-dev
BuildRequires : rasqal-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : unixODBC-dev
BuildRequires : zlib-dev

%description
Redland is a library that provides a high-level interface for RDF
(Resource Description Framework) implemented in an object-based API.
It is modular and supports different RDF parsers, serializers,
storage and query languages.  Redland is designed for developers to
provide RDF support in their applications as well as a core library
for RDF developers to start with.

%package bin
Summary: bin components for the redland package.
Group: Binaries
Requires: redland-data = %{version}-%{release}
Requires: redland-license = %{version}-%{release}

%description bin
bin components for the redland package.


%package data
Summary: data components for the redland package.
Group: Data

%description data
data components for the redland package.


%package dev
Summary: dev components for the redland package.
Group: Development
Requires: redland-lib = %{version}-%{release}
Requires: redland-bin = %{version}-%{release}
Requires: redland-data = %{version}-%{release}
Provides: redland-devel = %{version}-%{release}
Requires: redland = %{version}-%{release}

%description dev
dev components for the redland package.


%package doc
Summary: doc components for the redland package.
Group: Documentation
Requires: redland-man = %{version}-%{release}

%description doc
doc components for the redland package.


%package lib
Summary: lib components for the redland package.
Group: Libraries
Requires: redland-data = %{version}-%{release}
Requires: redland-license = %{version}-%{release}

%description lib
lib components for the redland package.


%package license
Summary: license components for the redland package.
Group: Default

%description license
license components for the redland package.


%package man
Summary: man components for the redland package.
Group: Default

%description man
man components for the redland package.


%prep
%setup -q -n redland-1.0.17
cd %{_builddir}/redland-1.0.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604603790
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604603790
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/redland
cp %{_builddir}/redland-1.0.17/COPYING %{buildroot}/usr/share/package-licenses/redland/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/redland-1.0.17/COPYING.LIB %{buildroot}/usr/share/package-licenses/redland/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/redland-1.0.17/LICENSE-2.0.txt %{buildroot}/usr/share/package-licenses/redland/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/redland-1.0.17/LICENSE.html %{buildroot}/usr/share/package-licenses/redland/506d48322c918f070819a1896f1769217a6b44de
cp %{_builddir}/redland-1.0.17/LICENSE.txt %{buildroot}/usr/share/package-licenses/redland/3152078c1f73982518fbb06d45eb7e5e0f25f147
cp %{_builddir}/redland-1.0.17/libltdl/COPYING.LIB %{buildroot}/usr/share/package-licenses/redland/3ac522f07da0f346b37b29cd73a60f79e992ffba
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rdfproc
/usr/bin/redland-config
/usr/bin/redland-db-upgrade

%files data
%defattr(-,root,root,-)
/usr/share/redland/Redland.i
/usr/share/redland/mysql-v1.ttl
/usr/share/redland/mysql-v2.ttl

%files dev
%defattr(-,root,root,-)
/usr/include/librdf.h
/usr/include/rdf_concepts.h
/usr/include/rdf_digest.h
/usr/include/rdf_hash.h
/usr/include/rdf_init.h
/usr/include/rdf_iterator.h
/usr/include/rdf_list.h
/usr/include/rdf_log.h
/usr/include/rdf_model.h
/usr/include/rdf_node.h
/usr/include/rdf_parser.h
/usr/include/rdf_query.h
/usr/include/rdf_raptor.h
/usr/include/rdf_serializer.h
/usr/include/rdf_statement.h
/usr/include/rdf_storage.h
/usr/include/rdf_storage_module.h
/usr/include/rdf_stream.h
/usr/include/rdf_uri.h
/usr/include/rdf_utf8.h
/usr/include/redland.h
/usr/lib64/librdf.so
/usr/lib64/pkgconfig/redland.pc
/usr/share/man/man3/redland.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/redland/home.png
/usr/share/gtk-doc/html/redland/index.html
/usr/share/gtk-doc/html/redland/index.sgml
/usr/share/gtk-doc/html/redland/indexes.html
/usr/share/gtk-doc/html/redland/introduction.html
/usr/share/gtk-doc/html/redland/left.png
/usr/share/gtk-doc/html/redland/objects.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-12-to-1-0-13.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-13-to-1-0-14.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-14-to-1-0-15.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-15-to-1-0-16.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-16-to-1-0-16.html
/usr/share/gtk-doc/html/redland/redland-changes.html
/usr/share/gtk-doc/html/redland/redland-concepts.html
/usr/share/gtk-doc/html/redland/redland-digest.html
/usr/share/gtk-doc/html/redland/redland-files.html
/usr/share/gtk-doc/html/redland/redland-general.html
/usr/share/gtk-doc/html/redland/redland-hash.html
/usr/share/gtk-doc/html/redland/redland-heuristics.html
/usr/share/gtk-doc/html/redland/redland-iterator.html
/usr/share/gtk-doc/html/redland/redland-list.html
/usr/share/gtk-doc/html/redland/redland-log.html
/usr/share/gtk-doc/html/redland/redland-model.html
/usr/share/gtk-doc/html/redland/redland-node.html
/usr/share/gtk-doc/html/redland/redland-parser.html
/usr/share/gtk-doc/html/redland/redland-query-results.html
/usr/share/gtk-doc/html/redland/redland-query.html
/usr/share/gtk-doc/html/redland/redland-serializer.html
/usr/share/gtk-doc/html/redland/redland-statement.html
/usr/share/gtk-doc/html/redland/redland-storage-module-file.html
/usr/share/gtk-doc/html/redland/redland-storage-module-hashes.html
/usr/share/gtk-doc/html/redland/redland-storage-module-memory.html
/usr/share/gtk-doc/html/redland/redland-storage-module-mysql.html
/usr/share/gtk-doc/html/redland/redland-storage-module-postgresql.html
/usr/share/gtk-doc/html/redland/redland-storage-module-sqlite.html
/usr/share/gtk-doc/html/redland/redland-storage-module-tstore.html
/usr/share/gtk-doc/html/redland/redland-storage-module-uri.html
/usr/share/gtk-doc/html/redland/redland-storage-module-virtuoso.html
/usr/share/gtk-doc/html/redland/redland-storage-modules.html
/usr/share/gtk-doc/html/redland/redland-storage.html
/usr/share/gtk-doc/html/redland/redland-stream.html
/usr/share/gtk-doc/html/redland/redland-unicode.html
/usr/share/gtk-doc/html/redland/redland-uri.html
/usr/share/gtk-doc/html/redland/redland-world.html
/usr/share/gtk-doc/html/redland/redland.devhelp2
/usr/share/gtk-doc/html/redland/redland.html
/usr/share/gtk-doc/html/redland/reference-manual.html
/usr/share/gtk-doc/html/redland/right.png
/usr/share/gtk-doc/html/redland/style.css
/usr/share/gtk-doc/html/redland/tutorial-introduction.html
/usr/share/gtk-doc/html/redland/tutorial.html
/usr/share/gtk-doc/html/redland/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/librdf.so.0
/usr/lib64/librdf.so.0.0.0
/usr/lib64/redland/librdf_storage_mysql.so
/usr/lib64/redland/librdf_storage_postgresql.so
/usr/lib64/redland/librdf_storage_sqlite.so
/usr/lib64/redland/librdf_storage_virtuoso.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/redland/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/redland/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/redland/3152078c1f73982518fbb06d45eb7e5e0f25f147
/usr/share/package-licenses/redland/3ac522f07da0f346b37b29cd73a60f79e992ffba
/usr/share/package-licenses/redland/506d48322c918f070819a1896f1769217a6b44de
/usr/share/package-licenses/redland/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/rdfproc.1
/usr/share/man/man1/redland-config.1
/usr/share/man/man1/redland-db-upgrade.1
