#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x43EC92504F71955A (dave@dajobe.org)
#
Name     : redland
Version  : 1.0.17
Release  : 2
URL      : http://download.librdf.org/source/redland-1.0.17.tar.gz
Source0  : http://download.librdf.org/source/redland-1.0.17.tar.gz
Source99 : http://download.librdf.org/source/redland-1.0.17.tar.gz.asc
Summary  : Redland RDF Application Framework
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 LGPL-2.1 LGPL-2.1+
Requires: redland-bin
Requires: redland-lib
Requires: redland-license
Requires: redland-man
Requires: redland-data
BuildRequires : db-dev
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : mariadb-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(raptor2)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : rasqal-dev
BuildRequires : sqlite-autoconf-dev
BuildRequires : unixODBC-dev
BuildRequires : zlib-dev

%description
Redland is a library that provides a high-level interface for RDF
(Resource Description Framework) implemented in an object-based API.
It is modular and supports different RDF parsers, serializers,
storage and query languages.  Redland is designed for developers to
provide RDF support in their applications as well as a core library
for RDF developers to start with.

%package bin
Summary: bin components for the redland package.
Group: Binaries
Requires: redland-data
Requires: redland-license
Requires: redland-man

%description bin
bin components for the redland package.


%package data
Summary: data components for the redland package.
Group: Data

%description data
data components for the redland package.


%package dev
Summary: dev components for the redland package.
Group: Development
Requires: redland-lib
Requires: redland-bin
Requires: redland-data
Provides: redland-devel

%description dev
dev components for the redland package.


%package doc
Summary: doc components for the redland package.
Group: Documentation
Requires: redland-man

%description doc
doc components for the redland package.


%package lib
Summary: lib components for the redland package.
Group: Libraries
Requires: redland-data
Requires: redland-license

%description lib
lib components for the redland package.


%package license
Summary: license components for the redland package.
Group: Default

%description license
license components for the redland package.


%package man
Summary: man components for the redland package.
Group: Default

%description man
man components for the redland package.


%prep
%setup -q -n redland-1.0.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533754870
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533754870
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/redland
cp COPYING %{buildroot}/usr/share/doc/redland/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/redland/COPYING.LIB
cp LICENSE-2.0.txt %{buildroot}/usr/share/doc/redland/LICENSE-2.0.txt
cp libltdl/COPYING.LIB %{buildroot}/usr/share/doc/redland/libltdl_COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rdfproc
/usr/bin/redland-config
/usr/bin/redland-db-upgrade

%files data
%defattr(-,root,root,-)
/usr/share/redland/Redland.i
/usr/share/redland/mysql-v1.ttl
/usr/share/redland/mysql-v2.ttl

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/librdf.so
/usr/lib64/pkgconfig/redland.pc
/usr/share/man/man3/redland.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/redland/home.png
/usr/share/gtk-doc/html/redland/index.html
/usr/share/gtk-doc/html/redland/index.sgml
/usr/share/gtk-doc/html/redland/indexes.html
/usr/share/gtk-doc/html/redland/introduction.html
/usr/share/gtk-doc/html/redland/left.png
/usr/share/gtk-doc/html/redland/objects.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-12-to-1-0-13.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-13-to-1-0-14.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-14-to-1-0-15.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-15-to-1-0-16.html
/usr/share/gtk-doc/html/redland/redland-changes-1-0-16-to-1-0-16.html
/usr/share/gtk-doc/html/redland/redland-changes.html
/usr/share/gtk-doc/html/redland/redland-concepts.html
/usr/share/gtk-doc/html/redland/redland-digest.html
/usr/share/gtk-doc/html/redland/redland-files.html
/usr/share/gtk-doc/html/redland/redland-general.html
/usr/share/gtk-doc/html/redland/redland-hash.html
/usr/share/gtk-doc/html/redland/redland-heuristics.html
/usr/share/gtk-doc/html/redland/redland-iterator.html
/usr/share/gtk-doc/html/redland/redland-list.html
/usr/share/gtk-doc/html/redland/redland-log.html
/usr/share/gtk-doc/html/redland/redland-model.html
/usr/share/gtk-doc/html/redland/redland-node.html
/usr/share/gtk-doc/html/redland/redland-parser.html
/usr/share/gtk-doc/html/redland/redland-query-results.html
/usr/share/gtk-doc/html/redland/redland-query.html
/usr/share/gtk-doc/html/redland/redland-serializer.html
/usr/share/gtk-doc/html/redland/redland-statement.html
/usr/share/gtk-doc/html/redland/redland-storage-module-file.html
/usr/share/gtk-doc/html/redland/redland-storage-module-hashes.html
/usr/share/gtk-doc/html/redland/redland-storage-module-memory.html
/usr/share/gtk-doc/html/redland/redland-storage-module-mysql.html
/usr/share/gtk-doc/html/redland/redland-storage-module-postgresql.html
/usr/share/gtk-doc/html/redland/redland-storage-module-sqlite.html
/usr/share/gtk-doc/html/redland/redland-storage-module-tstore.html
/usr/share/gtk-doc/html/redland/redland-storage-module-uri.html
/usr/share/gtk-doc/html/redland/redland-storage-module-virtuoso.html
/usr/share/gtk-doc/html/redland/redland-storage-modules.html
/usr/share/gtk-doc/html/redland/redland-storage.html
/usr/share/gtk-doc/html/redland/redland-stream.html
/usr/share/gtk-doc/html/redland/redland-unicode.html
/usr/share/gtk-doc/html/redland/redland-uri.html
/usr/share/gtk-doc/html/redland/redland-world.html
/usr/share/gtk-doc/html/redland/redland.devhelp2
/usr/share/gtk-doc/html/redland/redland.html
/usr/share/gtk-doc/html/redland/reference-manual.html
/usr/share/gtk-doc/html/redland/right.png
/usr/share/gtk-doc/html/redland/style.css
/usr/share/gtk-doc/html/redland/tutorial-introduction.html
/usr/share/gtk-doc/html/redland/tutorial.html
/usr/share/gtk-doc/html/redland/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/librdf.so.0
/usr/lib64/librdf.so.0.0.0
/usr/lib64/redland/librdf_storage_mysql.so
/usr/lib64/redland/librdf_storage_sqlite.so
/usr/lib64/redland/librdf_storage_virtuoso.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/redland/COPYING
/usr/share/doc/redland/COPYING.LIB
/usr/share/doc/redland/LICENSE-2.0.txt
/usr/share/doc/redland/libltdl_COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/rdfproc.1
/usr/share/man/man1/redland-config.1
/usr/share/man/man1/redland-db-upgrade.1
